OUTPUT_DIR: "./exp_cuhk"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "data/CUHK-SYSU"
SOLVER:
  MAX_EPOCHS: 20
MODEL:
  RPN:
    PRE_NMS_TOPN_TRAIN: 2000
    PRE_NMS_TOPN_TEST: 1000
    POST_NMS_TOPN_TRAIN: 1000
    POST_NMS_TOPN_TEST: 1000
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000